FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build-backend
WORKDIR /src
COPY ./src/Utgifter.slnx .
COPY ./src/Utgifter.Api ./Utgifter.Api
COPY ./src/Utgifter.Tests ./Utgifter.Tests

RUN dotnet restore Utgifter.slnx
RUN dotnet build -c Release --no-restore
RUN dotnet publish ./Utgifter.Api/Utgifter.Api.csproj -c Release -o /app --no-restore --no-build

FROM oven/bun:1-alpine as build-frontend
WORKDIR /src
COPY ./src/Utgifter.Site/ .

RUN bun install
RUN bunx --bun vite build

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS runtime
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Production
WORKDIR /app

COPY --from=build-backend /app ./
COPY --from=build-frontend /src/dist ./wwwroot
ENTRYPOINT ["dotnet", "Utgifter.Api.dll"]

LABEL org.opencontainers.image.source=https://github.com/ldellisola/utgifter
LABEL org.opencontainers.image.description="Utgifter (Expenses) is an expenses visualization tool"
LABEL org.opencontainers.image.licenses=MIT
