{
 "title": "Personal Economy",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "person",
    "label": "Person",
    "query": "select distinct person from expenses"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Expenses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(amount)\nFROM\n  expenses\nWHERE\n  person = '$person' and $__timeFilter(date) and shared = false"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date, amount, store,COALESCE(category, 'OTHER') as category\nFROM\n  expenses\nWHERE $__timeFilter(date) and person = '$person' and shared = false \norder by date desc"
    }
   ]
  },
  {
   "title": "Expenses per Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount) AS \"expenses\",\n  COALESCE(category, 'OTHER') as category\nFROM\n  expenses\nwhere $__timeFilter(date) and shared = false and person = '$person'\nGROUP BY\n  category"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "rawSql": "SELECT sum(amount) as total, COALESCE(category, 'OTHER') as category, date\nFROM expenses \nwhere $__timeFilter(date) and person = '$person'  and shared = false \nGROUP BY date, category\norder by category, date desc\n"
    }
   ]
  }
 ]
}