{
 "title": "Shared Economy",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "include_trip", "label": "Include Trips", "query": "true, false" }
  ]
 },
 "panels": [
  {
   "title": "Total Expenses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(amount)\nFROM\n  expenses\nWHERE  $__timeFilter(date) and shared = true  and ($include_trip or trip = $include_trip)"
    }
   ]
  },
  {
   "title": "Top 10 Most Expensive Purchases",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM\n  expenses\nWHERE  $__timeFilter(date) and shared = true  and ($include_trip or trip = $include_trip)\norder by  amount desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Top 10 Most Visited Shops",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "rawSql": "SELECT  store, sum(amount)\nFROM\n  expenses\nWHERE  $__timeFilter(date) and shared = true  and ($include_trip or trip = $include_trip)\ngroup by store\norder by sum(amount) desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Expenses per Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount) AS \"expenses\",\n  COALESCE(category, 'OTHER') as category\nFROM\n  expenses\nwhere $__timeFilter(date) and shared = true and ($include_trip or trip = $include_trip)\nGROUP BY\n  category"
    }
   ]
  },
  {
   "title": "Expenses per Day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "rawSql": "SELECT sum(amount) as total, COALESCE(category, 'OTHER') as category, date\nFROM expenses \nwhere $__timeFilter(date)  and shared = true  and ($include_trip or trip = $include_trip)\nGROUP BY date, category\norder by category, date desc\n"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  date, amount, store,COALESCE(category, 'OTHER') as category\nFROM\n  expenses\nWHERE $__timeFilter(date) and shared = true \norder by date desc"
    }
   ]
  }
 ]
}